### ISSUE TITLE
[PE-D][Tester A] Unlimited String Length for employees

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-3/tp#196]
<i><video controls><source src="https://raw.githubusercontent.com/LimJH2002/ped/main/files/e4d657ed-c46d-489e-b219-bc459260e248.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/LimJH2002/ped/main/files/e4d657ed-c46d-489e-b219-bc459260e248.mp4</i>

If the name and address inputs are too long, the viewing experience become not really nice, and also it is unlikely for a person's name and address to be longer than an essay.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LimJH2002/ped#3

**Comment by timleow** [comment]
Fixing this would be considered a feature enhancement, since we would have to tighten the validation for names and create a new error message to be displayed for long names. Hence, we will not fix it.

We will specify this behaviour in the user guide.
