### ISSUE TITLE
[PE-D][Tester D] Email prefix param can accept wrong domain

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-3/tp#200]
![image.png](https://raw.githubusercontent.com/ryamgoh/ped/main/files/02ce99ac-c589-4f36-b3eb-2e3fe9209f76.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ryamgoh/ped#2

**Comment by Chandan8186** [comment]
We will make the email address requirements more clear in the user guide. As amending the regex pattern would be considered a feature enhancement, we will not be doing so for v1.4.
